# site information
title: EF Log
description: The georeferenced photolog of data artist Emily Fuhrman.
baseurl: "/log"
url: "http://emilyfuhrman.co"

# post settings
defaults:
  - scope:
      path: ''
      type: posts
    values:
      category: entries
      layout: post
      permalink: /:categories/:year/:title:output_ext

# formatting
sass:
  style: compressed